# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Modul59\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1081, 71))
        self.groupBox.setObjectName("groupBox")
        self.reestr = QtWidgets.QToolButton(self.groupBox)
        self.reestr.setGeometry(QtCore.QRect(10, 20, 91, 35))
        self.reestr.setObjectName("reestr")
        self.load_reestr = QtWidgets.QToolButton(self.groupBox)
        self.load_reestr.setGeometry(QtCore.QRect(120, 20, 91, 35))
        self.load_reestr.setObjectName("load_reestr")
        self.operations_59 = QtWidgets.QToolButton(self.groupBox)
        self.operations_59.setGeometry(QtCore.QRect(230, 20, 91, 35))
        self.operations_59.setObjectName("operations_59")
        self.operations = QtWidgets.QToolButton(self.groupBox)
        self.operations.setGeometry(QtCore.QRect(340, 20, 91, 35))
        self.operations.setObjectName("operations")
        self.help = QtWidgets.QToolButton(self.groupBox)
        self.help.setGeometry(QtCore.QRect(450, 20, 91, 35))
        self.help.setObjectName("help")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 1071, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(150, 30, 31, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(900, 30, 47, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(510, 30, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(750, 30, 31, 20))
        self.label_5.setObjectName("label_5")
        self.untb = QtWidgets.QLineEdit(self.groupBox_2)
        self.untb.setGeometry(QtCore.QRect(60, 30, 81, 20))
        self.untb.setObjectName("untb")
        self.fio = QtWidgets.QLineEdit(self.groupBox_2)
        self.fio.setGeometry(QtCore.QRect(180, 30, 321, 20))
        self.fio.setObjectName("fio")
        self.dul = QtWidgets.QLineEdit(self.groupBox_2)
        self.dul.setGeometry(QtCore.QRect(780, 30, 113, 20))
        self.dul.setObjectName("dul")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 111, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(380, 60, 161, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(210, 60, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(620, 60, 71, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(770, 60, 51, 20))
        self.label_10.setObjectName("label_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 90, 1041, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comment = QtWidgets.QLineEdit(self.groupBox_3)
        self.comment.setGeometry(QtCore.QRect(10, 20, 1021, 81))
        self.comment.setObjectName("comment")
        self.newStatusPB = QtWidgets.QComboBox(self.groupBox_2)
        self.newStatusPB.setGeometry(QtCore.QRect(130, 60, 69, 22))
        self.newStatusPB.setObjectName("newStatusPB")
        self.inoBank = QtWidgets.QComboBox(self.groupBox_2)
        self.inoBank.setGeometry(QtCore.QRect(300, 60, 69, 22))
        self.inoBank.setObjectName("inoBank")
        self.oes = QtWidgets.QComboBox(self.groupBox_2)
        self.oes.setGeometry(QtCore.QRect(540, 60, 69, 22))
        self.oes.setObjectName("oes")
        self.control = QtWidgets.QComboBox(self.groupBox_2)
        self.control.setGeometry(QtCore.QRect(690, 60, 69, 22))
        self.control.setObjectName("control")
        self.sanction = QtWidgets.QComboBox(self.groupBox_2)
        self.sanction.setGeometry(QtCore.QRect(820, 60, 69, 22))
        self.sanction.setObjectName("sanction")
        self.statusPB = QtWidgets.QComboBox(self.groupBox_2)
        self.statusPB.setGeometry(QtCore.QRect(950, 30, 111, 22))
        self.statusPB.setObjectName("statusPB")
        self.birthdate = QtWidgets.QLineEdit(self.groupBox_2)
        self.birthdate.setGeometry(QtCore.QRect(630, 30, 113, 20))
        self.birthdate.setObjectName("birthdate")
        self.QCalendar = QtWidgets.QToolButton(self.groupBox_2)
        self.QCalendar.setGeometry(QtCore.QRect(600, 30, 25, 19))
        self.QCalendar.setObjectName("QCalendar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 390, 1081, 471))
        self.groupBox_4.setObjectName("groupBox_4")
        self.MainReestr = QtWidgets.QTableView(self.groupBox_4)
        self.MainReestr.setGeometry(QtCore.QRect(10, 20, 1061, 441))
        self.MainReestr.setObjectName("MainReestr")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 310, 1081, 80))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.StatusPB = QtWidgets.QToolButton(self.tab_1)
        self.StatusPB.setGeometry(QtCore.QRect(10, 10, 110, 35))
        self.StatusPB.setObjectName("StatusPB")
        self.DelPB = QtWidgets.QToolButton(self.tab_1)
        self.DelPB.setGeometry(QtCore.QRect(130, 10, 110, 35))
        self.DelPB.setObjectName("DelPB")
        self.RefreshPB = QtWidgets.QToolButton(self.tab_1)
        self.RefreshPB.setGeometry(QtCore.QRect(250, 10, 110, 35))
        self.RefreshPB.setObjectName("RefreshPB")
        self.search = QtWidgets.QLineEdit(self.tab_1)
        self.search.setGeometry(QtCore.QRect(370, 10, 411, 31))
        self.search.setObjectName("search")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Панель инструментов:"))
        self.reestr.setText(_translate("MainWindow", "reestr"))
        self.load_reestr.setText(_translate("MainWindow", "load reestr"))
        self.operations_59.setText(_translate("MainWindow", "operations_59"))
        self.operations.setText(_translate("MainWindow", "operations"))
        self.help.setText(_translate("MainWindow", "help"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Сведения из реестра:"))
        self.label.setText(_translate("MainWindow", "ФИО:"))
        self.label_2.setText(_translate("MainWindow", "УНТБ:"))
        self.label_3.setText(_translate("MainWindow", "Статус:"))
        self.label_4.setText(_translate("MainWindow", "Дата рождения:"))
        self.label_5.setText(_translate("MainWindow", "ДУЛ:"))
        self.label_6.setText(_translate("MainWindow", "Присвоение статуса:"))
        self.label_7.setText(_translate("MainWindow", "Отказ в совершении операции:"))
        self.label_8.setText(_translate("MainWindow", "Запрос инобанка:"))
        self.label_9.setText(_translate("MainWindow", "На контроле:"))
        self.label_10.setText(_translate("MainWindow", "Санкции:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Комментарий:"))
        self.QCalendar.setText(_translate("MainWindow", "..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Основной реестр:"))
        self.StatusPB.setText(_translate("MainWindow", "Добавить клиента"))
        self.DelPB.setText(_translate("MainWindow", "Удалить строку"))
        self.RefreshPB.setText(_translate("MainWindow", "Обновить таблицу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Работа с таблицей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Присвоение статуса"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Инобанк"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Отказ"))

