# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 1171, 571))
        self.groupBox.setObjectName("groupBox")
        self.MainReestr = QtWidgets.QTableView(self.groupBox)
        self.MainReestr.setGeometry(QtCore.QRect(10, 20, 1151, 541))
        self.MainReestr.setObjectName("MainReestr")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 1051, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.search = QtWidgets.QLineEdit(self.groupBox_2)
        self.search.setGeometry(QtCore.QRect(470, 30, 351, 31))
        self.search.setObjectName("search")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(320, 30, 151, 31))
        self.label.setObjectName("label")
        self.refreshButton = QtWidgets.QPushButton(self.groupBox_2)
        self.refreshButton.setGeometry(QtCore.QRect(10, 20, 281, 41))
        self.refreshButton.setObjectName("refreshButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 1041, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 51, 21))
        self.label_2.setObjectName("label_2")
        self.use_chip = QtWidgets.QLineEdit(self.groupBox_3)
        self.use_chip.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.use_chip.setObjectName("use_chip")
        self.merchant_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.merchant_name.setGeometry(QtCore.QRect(280, 30, 113, 20))
        self.merchant_name.setObjectName("merchant_name")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(400, 30, 71, 21))
        self.label_4.setObjectName("label_4")
        self.merchant_city = QtWidgets.QLineEdit(self.groupBox_3)
        self.merchant_city.setGeometry(QtCore.QRect(480, 30, 113, 20))
        self.merchant_city.setObjectName("merchant_city")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(610, 30, 81, 21))
        self.label_5.setObjectName("label_5")
        self.merchant_state = QtWidgets.QLineEdit(self.groupBox_3)
        self.merchant_state.setGeometry(QtCore.QRect(700, 30, 113, 20))
        self.merchant_state.setObjectName("merchant_state")
        self.zip = QtWidgets.QLineEdit(self.groupBox_3)
        self.zip.setGeometry(QtCore.QRect(40, 60, 113, 20))
        self.zip.setObjectName("zip")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 21, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(160, 60, 31, 21))
        self.label_7.setObjectName("label_7")
        self.mcc = QtWidgets.QLineEdit(self.groupBox_3)
        self.mcc.setGeometry(QtCore.QRect(190, 60, 113, 20))
        self.mcc.setObjectName("mcc")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(310, 60, 51, 21))
        self.label_8.setObjectName("label_8")
        self.amount = QtWidgets.QLineEdit(self.groupBox_3)
        self.amount.setGeometry(QtCore.QRect(360, 60, 113, 20))
        self.amount.setObjectName("amount")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(790, 60, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(480, 60, 51, 21))
        self.label_10.setObjectName("label_10")
        self.control = QtWidgets.QLineEdit(self.groupBox_3)
        self.control.setGeometry(QtCore.QRect(880, 30, 61, 20))
        self.control.setObjectName("control")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(830, 30, 41, 21))
        self.label_11.setObjectName("label_11")
        self.comment = QtWidgets.QLineEdit(self.groupBox_3)
        self.comment.setGeometry(QtCore.QRect(10, 110, 1011, 91))
        self.comment.setObjectName("comment")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_12.setObjectName("label_12")
        self.tmp_datetime = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.tmp_datetime.setGeometry(QtCore.QRect(540, 60, 194, 22))
        self.tmp_datetime.setObjectName("tmp_datetime")
        self.tmp_date = QtWidgets.QDateEdit(self.groupBox_3)
        self.tmp_date.setGeometry(QtCore.QRect(830, 60, 110, 22))
        self.tmp_date.setObjectName("tmp_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Реестр:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Работа с таблицей:"))
        self.label.setText(_translate("MainWindow", "Фильтр по второй колонке:"))
        self.refreshButton.setText(_translate("MainWindow", "Обновить строку данными из верхней части"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Поля реестра:"))
        self.label_2.setText(_translate("MainWindow", "Use Chip:"))
        self.label_3.setText(_translate("MainWindow", "Merchant Name:"))
        self.label_4.setText(_translate("MainWindow", "Merchant City:"))
        self.label_5.setText(_translate("MainWindow", "Merchant State:"))
        self.label_6.setText(_translate("MainWindow", "zip:"))
        self.label_7.setText(_translate("MainWindow", "MCC:"))
        self.label_8.setText(_translate("MainWindow", "Amount:"))
        self.label_9.setText(_translate("MainWindow", "Date:"))
        self.label_10.setText(_translate("MainWindow", "Datetime:"))
        self.label_11.setText(_translate("MainWindow", "Control:"))
        self.label_12.setText(_translate("MainWindow", "comment:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

